decoration {
    rounding = 10
}

general {
    border_size = 4
}

input {
    kb_layout = latam
}

# media keys
bindd = , XF86HomePage, Omarchy menu, exec, omarchy-menu
bindd = , XF86Mail, Email, exec, omarchy-launch-browser

# web apps
bindd = SUPER SHIFT, L, Lichess, exec, omarchy-launch-webapp "https://lichess.org"
bindd = SUPER, Z, Cursor, exec, cursor
bindd = SUPER SHIFT, Z, Code, exec, code

# monitors
bind = SUPER, U, focusmonitor, +1
bind = SUPER SHIFT, U, movewindow, mon:+1
bind = SUPER SHIFT, P,  movecurrentworkspacetomonitor, +1
# added that to mimic i3's behavior
# where pushing a workspace to another monitor also focuses it
bind = SUPER SHIFT, P, focusmonitor, +1
# credits
# reddit.com/r/hyprland/comments/1ak1pta/move_workspace_to_another_monitor/