decoration {
    rounding_power = 3
    rounding = 10
}

# virt manager 100% opacity
windowrule = opacity 1 1, title:^(.* on QEMU/KVM)$

# media keys
bindd = , XF86HomePage, Omarchy menu, exec, omarchy-menu
bindd = , XF86Mail, Email, exec, omarchy-launch-browser
bindd = , XF86Tools, Bluetooth, exec, ~/dev/scripts/bash/toggle-bluetooth.sh
# bindld = , XF86Calculator

# floating default size
windowrulev2 = size 960 540, floating:1
